Vonage/vivid

- common/core/readme.md
https://jira.vonage.com/browse/VIV-764
> chore(docs): fixed documentation bug

- components/side-drawer/src/vwc-side-drawer-base.ts
> refactor(vwc-side-drawer): refactor top-bar to use top-app-bar

- components/empty-state/src/vwc-empty-state.scss
> fix(empty-state): base reset z-index

- common/design-tokens/package.json
- components/text/package.json
> build(text): dt dependency type

- .github/workflows/release.yml
> ci(announcement): remove release slack integration

- components/calendar/package.json
- components/card/package.json
> fix(card): declare missing dependencies

- components/accordion/stories/accordion.stories.js
- components/expansion-panel/stories/expansion-panel.stories.js
> fix(accordion): accordion outlined with elevation wrap

- package.json
- yarn.lock
> chore(browserslist): update caniuse lite

- components/side-drawer/src/vwc-side-drawer-base.ts
> fix(side-drawer): uncomment blocking elements import

- components/card/src/vwc-card.scss
> chore(card): adopt to host height

- package.json
- yarn.lock
> build(workspace): minimist vulnerable version update

- components/list/src/vwc-list-item.scss
- scripts/release_announcer/index.js
> chore(list): remove ripple focus from activated item

- components/button/src/vwc-button.scss
> fix(button): icon initialized to current color

- components/dialog/src/vwc-dialog.scss
- components/dialog/stories/dialog.stories.js
> chore(dialog): fix action top padding style

- common/fonts/test/fonts.test.js
- components/popup/src/vwc-popup-base.ts
- components/popup/test/popup.test.js
> test(popup): remove flaky tests

- components/button-toggle-group/src/vwc-button-toggle-group.ts
- components/button-toggle-group/test/toggle-buttons-group.test.js
@k-paxian - would appreciate if you could review this one and make sure it answers the use case (note [the test I've added](https://github.com/Vonage/vivid/blob/37dbad688fcd2a07ae29f86d06d5836dffbdef9c/components/button-toggle-group/test/toggle-buttons-group.test.js#L313))
> fix(button-toggle-group): fix race condition between values property and slotted buttons

- components/card/readme.md
> docs(card): outdated slot name

- components/popup/src/vwc-popup-base.ts
> fix(popup): remove anchorEl property

- components/button/src/vwc-button.scss
> chore(button): reduce line-height to support 2 lines

- components/button/src/vwc-button.scss
- components/button/test/button.typography.test.js
> fix(button): apply line height through var

- components/button/src/vwc-button.scss
- components/button/test/button.typography.test.js
> refactor(button): revert line height changes to normal

- common/context/test/context.test.js
- common/fonts/test/fonts.test.js
- components/audio/src/vwc-audio.ts
- components/audio/test/audio.test.js
Fixes issue: https://jira.vonage.com/browse/VIV-872
> fix(vwc-audio): can now change src while playing
